### PR TITLE
Remove VM only when it exists, do nothing otherwise

### PR DESCRIPTION
**Pull request by mkasztelnik**
Fixes problem with failing jobs, when trying to delete not existing VMs

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@nowakowski, @tbartynski please take a look

**Comment by tbartynski** [comment]
:+1:

**Comment by Nuanda** [comment]
Is it possible to do that from the Admin UI?

**Comment by nowakowski** [comment]
@Nuanda Individual VMs cannot be deleted from the admin UI (you can only remove an entire ApplianceSet, which will trigger `destroy` on all underlying VMs). This ticket, however, is about fixing an inefficient worker - not about improving the UI.

**Comment by Nuanda** [comment]
I know - just asking.

**Comment by nowakowski** [comment]
Oh, okay then. :)

**Pull request merged**
