### PR TITLE
Rackspace integration

### PR DESCRIPTION
**Pull request by mkasztelnik**
In the scope of this PR rackspace compute site integration will be implemented. To make it possible following actions need to be supported:

  * [x] Get flavors (`FlavorManager`)
  * [x] Get flavor data (`FlavorManager`)
  * [x] Get vms (`VmMonitoringWorker`)
  * [x] Get vm data (`VmUpdater`)
  * [x] Create tags for vm (`VmTagsCreator`)
  * [x] Get templates	 (`VmTemplateMonitoringWorker`)
  * [x] Destroy vm (`VirtualMachine`)
  * [x] Managing vm (`VirtualMachine`)
  * [x] Save template	(`VirtualMachineTemplate`)
  * [x] Destroy template (`VirtualMachineTemplate`)
  * [x] Create vm (`VmCreator`)
  * [x] Import key pair (`UserKey`)
  * [x] Delete key pair (`UserKey`)
  * [x] Get template data (`VmtUpdater`)

### CODE REVIEW

**Comment by mkasztelnik** [comment]
Rackspace integration ready, @dice-cyfronet/atmo-dev-team please take a look

**Comment by Nuanda** [comment]
:+1:

**Comment by paoolo** [comment]
Why there is many bullets in first comment, but only 15 lines are changed and rest are added as configuration. Everything other is included in dependencies? Anyway :+1:

**Comment by mkasztelnik** [comment]
14 (not 15 :smile:) bullets are a checklist what need to be supported by concrete cloud provider. Rackspace is quite similar to openstack, that is why there so many changes.

**Comment by paoolo** [comment]
I counted lines which are changed by your commits, but not added as new. OK, again: :+1:

**Pull request merged**
