### PR TITLE
Pause and start actions in appliance rest API

### PR DESCRIPTION
**Pull request by mkasztelnik**
Required by https://jira.plgrid.pl/jira/browse/PLGCZ-40

### CODE REVIEW

**Comment by dharezlak** [comment]
@mkasztelnik: In order to properly enable/disable the Save button appliance_type_id needs to be provided by atmo in the /clew/appliance_instances action.

**Comment by mkasztelnik** [comment]
deployed into cloud-dev for tests

**Comment by dharezlak** [comment]
OK, clew is in place so we are ready for testing.

**Comment by mkasztelnik** [comment]
Deployed into cloud-dev

**Pull request merged**
