### PR TITLE
Allow delete non managed VM from Atmosphere DB

### LINKED ISSUE #225: Monitoring is not able to remove VM started outside atmosphere
Scenario:
  * start VM using e.g. nova client (`managed_by_atmosphere` should be set to false in atmosphere VM)
  * remove VM using e.g. nova client

as a result VM cannot be removed from atmosphere because of https://github.com/dice-cyfronet/atmosphere/blob/master/app/models/atmosphere/virtual_machine.rb#L233-L238

### PR DESCRIPTION
**Pull request by mkasztelnik**
Fix #225 

/cc @dice-cyfronet/atmo-dev-team please take a look

### CODE REVIEW

**Comment by tbartynski** [comment]
The code looks fine, however I guess there used to be such a guard for a reason. I can't think of it now. Since we check if vm is managed by Atmosphere in VM model before we actually delete it in cloud your modification seems safe, however I would recommend to have someone else to look at this PR also.
 Shy :+1:

**Comment by mkasztelnik** [comment]
IMHO this is safe. When we delete VM which is not managed by atmosphere it is deleted only from Atmosphere DB, not from the cloud. So during next VM monitoring worker it will be recreated :)

**Comment by mkasztelnik** [comment]
This PR should be also backported into stable branch.

**Comment by nowakowski** [comment]
:+1:

**Comment by mkasztelnik** [comment]
also cherry-picket into stable branch

**Pull request merged**
