### PR TITLE
Externalize and improve AT controller messages

### LINKED ISSUE #137: Improve conflict message
Please take a look at @nowakowski comment: https://github.com/dice-cyfronet/atmosphere/pull/134#discussion_r27882797

### PR DESCRIPTION
**Pull request by mkasztelnik**
Fixes #137

@dice-cyfronet/atmo-dev-team please take a look

### CODE REVIEW

**Comment by nowakowski** [comment]
:+1:  (unless Travis throws up.)

**Comment by nowakowski** [comment]
Sorry, misclick.

**Comment by mkasztelnik** [comment]
Rebased into latest master

**Comment by Nuanda** [comment]
:+1:

**Pull request merged**
