### PR TITLE
Extensions for setting additional params while creating appliance set and appliance

### PR DESCRIPTION
**Pull request by mkasztelnik**
It is required to implement support for user team in the scope of plgrid project.

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@dice-cyfronet/atmo-dev-team please take a look. It is required to add team support in the scope of plgrid poroject.

**Comment by Nuanda** [comment]
:+1:

**Comment by Nuanda** [comment]
@tbartynski @bwilk review, please.

**Comment by tbartynski** [comment]
:+1:

**Pull request merged**
