### PR TITLE
200 and 204 as success while deleting dnat redirection

### PR DESCRIPTION
**Pull request by mkasztelnik**
Necessary changes required when dice-cyfronet/ip-wrangler#7 PR will be merged and deployed.

Introduced changes are backward compatible.

/cc @dice-cyfronet/atmo-dev-team please take a look

### CODE REVIEW

**Comment by paoolo** [comment]
Response body will be examined? If DELETE return 200 it will return JSON table with hashes pointed to removed DNAT rules.

**Comment by mkasztelnik** [comment]
Nop, we don't care :smile:

**Comment by paoolo** [comment]
OK.

**Comment by Nuanda** [comment]
:+1:

**Comment by paoolo** [comment]
:+1:

**Pull request merged**
