### PR TITLE
testing ruby 2.1.4

### PR DESCRIPTION
**Pull request by mkasztelnik**

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@dice-cyfronet/atmo-dev-team please take a look

**Comment by nowakowski** [comment]
:+1:

**Comment by nowakowski** [comment]
Works for me (already tested in my branch).

**Comment by tbartynski** [comment]
I'm using rvm and with Ruby 2.1.4 both guard and rspec fails. If I set Ruby 2.1.2 in this branch I can run tests. I can't give plus one since it does not work for me but it is not a blocker from my point of view.

**Comment by mkasztelnik** [comment]
Ok so merging since it helps travis and in my local env.

**Pull request merged**
