### PR TITLE
Remove http_https PMT application protocol

### LINKED ISSUE #154: Enable redirecting http traffic to secured upstream servers
Currently only http upstream servers can be used. This will require to also change the external interface configuration form in MI's cloud views and atmosphere's REST API to convey the additional attribute saying if the upstream server is secured with https.

### PR DESCRIPTION
**Pull request by mkasztelnik**
This is not backward compatible change. Previously all http/https redirections were redirected into http, so it looked like that:

```
http  -> proxy -> http
https -> proxy-> http
```
This PR changes it into:

```
http  -> proxy -> http
https -> proxy -> https
```
That is why from the list of allowed values in
`PortMappingTemplate.application_type` `http_https` was removed.

What is more in `lib/support/redurys` you can find templates for redirus configuration (by mistake committed in 615e71a868c8d96fe558e54ec1826482b756055c :cry:).

Fix #154

### CODE REVIEW

**Comment by mkasztelnik** [comment]
I thing missing is CLEW update where `http_https` is removed from the UI. @dharezlak can you deal with it and commit clew update to this PR?

**Comment by mkasztelnik** [comment]
It is already deployed into vph-dev. You can test it there (please don't use http_https type - it will be removed from the UI).

**Comment by dharezlak** [comment]
clew was successfully updated

**Comment by mkasztelnik** [comment]
@nowakowski, @tbartynski please take a look (it is deployed into vph-dev).

**Comment by tbartynski** [comment]
@mkasztelnik Wanted to test this on vph-dev but I've got 502 Bad Gateway.
initctl status atmosphere => atmosphere stop/waiting

Seems like someone stopped it manually or deployment process failed?

**Comment by mkasztelnik** [comment]
I forgot to turn it on. Not it is working

**Comment by tbartynski** [comment]
Works for me :+1:

**Pull request merged**
