### PR TITLE
appliance types allowed params customization

### PR DESCRIPTION
**Pull request by mkasztelnik**
Changes required to fix [this spec](https://github.com/VPH-Share/atmosphere-vph/blob/master/spec/requests/atmosphere/appliance_types_spec.rb) in vph deployment.

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@dice-cyfronet/atmo-dev-team please take a look

**Comment by tbartynski** [comment]
:+1:

**Comment by nowakowski** [comment]
Same travis error as before.

**Comment by nowakowski** [comment]
:+1:

**Pull request merged**
