### PR TITLE
Atmosphere generators and engine docs

### LINKED ISSUE #6: Atmosphere engine documentation
Currently we have atmosphere documentation specific for rails application. It should be updated to reflect the way how `atmosphere engine` should be used.

### PR DESCRIPTION
**Pull request by mkasztelnik**
TODOs:

  - [x] @mkasztelnik: install generator
  - [x] @mkasztelnik: extensions generator
  - [x] @mkasztelnik: atmosphere engine docs
  - [x] @nowakowski general Atmosphere description in `README.md` 
  - [x] @nowakowski: proofreading

Fixes #6

### CODE REVIEW

**Comment by mkasztelnik** [comment]
Generators and engine usage created. @nowakowski please add generic atmosphere description into `README.md` and do the proofreading.

**Comment by mkasztelnik** [comment]
@nowakowski most probably some configuration is also necessary for billing system. We should also mention about it int README.md and maybe in [install generator README](https://github.com/dice-cyfronet/atmosphere/blob/doc/lib/generators/templates/README). I will add additional checkbox for it in PR description.

**Comment by nowakowski** [comment]
@mkasztelnik I have complied with your requests - except as regards the billing system. @Nuanda has recently developed a GUI for creating and managing funds; this obviously changes the way in which the billing system can be kickstarted (instead of throwing "magic" commands at the console users can now navigate to the admin GUI and click their way to success) - I will be happy to add a suitable description to the GUI manual; however I am unsure where this manual is to be found (or indeed if it exists at all). Please advise.

**Comment by mkasztelnik** [comment]
@nowakowski thx for introduction it is really nice :smile:. We don't have section devoted UI. I also realized that also sections specific for tcp/udp, http/https redirections are missing. We should add it in the scope of further PR. I will create separate issues for these elements.

**Comment by mkasztelnik** [comment]
@Nuanda, @bwilk, @tbartynski please take a look.

**Comment by nowakowski** [comment]
:+1:

**Comment by Nuanda** [comment]
:+1:

**Pull request merged**
