### PR TITLE
sanitize public key content

### PR DESCRIPTION
**Pull request by tbartynski**
Fix https://github.com/dice-cyfronet/atmosphere/issues/259

### CODE REVIEW

**Comment by mkasztelnik** [comment]
Please fix errors reported by hound

**Comment by mkasztelnik** [comment]
I believe that regexp can be used here and first valid ssh public key can be taken. It should simplify code.

**Comment by mkasztelnik** [comment]
:+1: but why `Gemfile.lock` is changed?

**Comment by tbartynski** [comment]
Gemfile.lock modified by accident. Reverted this change.

**Pull request merged**
