### PR TITLE
ignore destroy on cloud not found exception

### LINKED ISSUE #50: Ignore 404 fog response code while deleting VM, VMT
The process of deleting VM, VMT should ignore 404 fog response code - if VM or VMT was already deleted by "something" on the compute site than it is OK - we only need to remove this object from our database

Following error should be ignored:

```
Fog::Compute::OpenStack::NotFound: Expected(204) <=> Actual(404 Not Found)
excon.error.response
  :body          => "{\"itemNotFound\": {\"message\": \"Instance could not be found\", \"code\": 404}}"
  :headers       => {
    "Content-Length"       => "73"
    "Content-Type"         => "application/json; charset=UTF-8"
    "Date"                 => "Tue, 16 Dec 2014 11:55:54 GMT"
    "X-Compute-Request-Id" => "reqxxx"
  }
  :local_address => "xxx.xxx.xxx.xxx"
  :local_port    => 58700
  :reason_phrase => "Not Found"
  :remote_ip     => "xxx.xxx.xxx.xxx"
  :status        => 404
```

### PR DESCRIPTION
**Pull request by mkasztelnik**
We should not care about VM, VMT not found exception thrown by compute site when destroying `Atmosphere::VirtualMachine`, `Atmosphere::VirtualMachineTemplate`.

Fixes #50

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@nowakowski, @Nuanda please take a look

**Comment by mkasztelnik** [comment]
log level raised to `warn`

**Comment by Nuanda** [comment]
:+1:

**Comment by tbartynski** [comment]
:+1:

**Pull request merged**
